### DISCUSSION TITLE
Are variables nested in wildcards possible?

### DISCUSSION THREAD

**Discussion by anothertal3** [adieyal/sd-dynamic-prompts#613] [Q&A] [answered]
Hello and thank you for a very useful extension.

I've recently stumbled about a usecase which I'm unable to solve on my own.

Here's a simplified example using the following wildcards file (*.yaml):
```yaml
cars:
  ford:
    name:
      - Ford
    types:
      - muscle car
      - compact car
      - roadster
    colors:
      - white
      - black
      - brown
      - red

  porsche:
    name:
      - Porsche
    types:
      - sports car
    colors:
      - red
      - black

  john_deere:
    name:
      - John Deere
    types:
      - tractor
    colors:
      - green
      - yellow  
```

Now I would like to generate dynamic images of cars with consistent and matching colors, e.g.:
- a tractor made by John Deere, standing in a rusty old workshop, green
- a sports car made by Porsche, standing in a rusty old workshop, red
- a roaster made by Ford, standing in a rusty old workshop, white

I hoped that something along the following lines would work:
```
${car=!{ford|porsche|john_deere}}
a __cars/${car}/types__ made by __cars/${car}/name__, standing in a rusty old workshop, __cars/${car}/colors__
```

But this only results in an exception. I've made similar attempts but wasn't successful. 

Is something like this even supported? Or can it be achieved by using a workaround/different structuring?

Thank you!
