### ISSUE TITLE
YAML files not updating when saved without reloading UI

### ISSUE THREAD

**Issue by andrewletz** [adieyal/sd-dynamic-prompts#500]
I tried using .yaml files for my RNG prompts since I want to use whitespace in them, but when trying to mess with a .yaml file I noticed it does not update the prompts without having to reload the entire webUI. For example, with the following .yaml file:

```
vala:
  prompts:
    one:
      - |
        #zzzz
        test prompt
    two:
      - |
        #test
        another test
```

I added "two", and when using __vala/prompts/two__ it does not output "another test", but outputs __vala/prompts/two__. After reloading the UI it outputs as expected ("another test").

Is this a bug or a con of using .yaml? I need to update my prompts in real time to test them so this kinda ruins the whole prospect of .yaml if its not a bug.

Thanks.
