### ISSUE TITLE
[BUG] dynamicprompts 0.30.1 is broken

### ISSUE THREAD

**Issue by acorderob** [adieyal/sd-dynamic-prompts#665]
The new version of the library does not generate correct prompts. The result is all f****ed up with missing parts and partial statements.

Reverting to the commit prior to this change (e07ff1d72abfb1f9f4ae5b094e5e3ab173aeebde) fixes it.

**Comment by akx** [comment]
Can you be a bit more specific than "all f****ed up with missing parts and partial statements"? What is your original prompt? What are the results? Are there errors or warnings in the webui console?

**Comment by acorderob** [comment]
I just tested that wildcard by itself, and it fails.

The view.yaml file contains (among other wildcards):

```yaml
view:
  verticalangle_landscape:
    - "{3::|looking up view|looking down view|birds-eye view}"
```

And prompting with `__view/verticalangle_landscape__` results in

`|looking up view|looking down view|birds-eye view}`

So you should be able to reproduce.
