### ISSUE TITLE
Variables not support `,` Comma , `(` parenthesis

### ISSUE THREAD

**Issue by bluelovers** [adieyal/sd-dynamic-prompts#779]
| Variables               | output                      |
|-------------------------|-----------------------------|
| `(who=young woman\,)`   | `young woman\ wearing xxxx` |
| `(who=young woman,)`    | `young woman wearing xxxx`  |
| `(who=(young woman))`   | X                           |
| `(who=\(young woman\))` | X                           |

----------

```yaml
lazy-test:
  # Prompt only a ballerina costume
  prompt-costume:
    - >-
      ${who:ballerina} wearing xxxx
  # Prompt ballerina costume with girl and location
  prompt-full:
    - >-
      __lazy-test/prompt-costume(who=\(__lazy-test/beauty-adj__ ballerina\) young woman,)__,
      set in yyy {, at night|, at sunset|}
  beauty-adj:
    - sexy
    - angelic
    - attractive
    - bonnie
    - desirable
    - esthetic
    - gorgeous
    - lovely
    - supermodel
    - vivacious
```
