### ISSUE TITLE
support new SYNTAX something like `__&wildcard__` in yaml

### ISSUE THREAD

**Issue by bluelovers** [adieyal/sd-dynamic-prompts#791]
```yaml
test-wildcards-root:
  # new Syntax
  random1:
    # should for return >= 2
    - >-
      {2-$$__test-wildcards-root/a1__}
    # should for return >= 3
    - >-
      {3-$$__test-wildcards-root/a3__}
    # should for return >= 6
    - >-
      {6-$$__test-wildcards-root/a4__}
  # new Syntax for make a1 = [bbb1, bbb2, bbb3, bbb4]
  a1:
    - __&test-wildcards-root/b1__
  # new Syntax for make a3 = [bbb1, bbb2, bbb3, bbb4, a333]
  a3:
    - __&test-wildcards-root/b1__
    - a333
  # new Syntax for make a4 = [bbb1, bbb2, bbb3, bbb4, b222, b2222, b22222, a333]
  a4:
    - __&test-wildcards-root/b*__
    - a333
  # current always return only 1
  random2:
    - >-
      {2-$$__test-wildcards-root/a2__}
  a2:
    - __test-wildcards-root/b1__
  b1:
    - bbb1
    - bbb2
    - bbb3
    - bbb4
  b2:
    - b222
    - b2222
    - b22222
```
