### ISSUE TITLE
bug: min range not work

### ISSUE THREAD

**Issue by bluelovers** [adieyal/sd-dynamic-prompts#794]
```
{4-$$__lazy-wildcards/subject/art-type/sketch-pen-base/style__}
```

should always get >= 4, but it only >= 1

```yaml
lazy-wildcards:
  subject:
    art-type:
      sketch-pen-landscape:
        prompts:
          - >-
            __lazy-wildcards/subject/art-type/sketch-pen-landscape/main__,
            __lazy-wildcards/subject/art-type/sketch-pen-base/prompts__
        main:
          - (XCYP) Landscape Sketch, (Sketch Landscape:1.4)
      sketch-pen-portrait:
        prompts:
          - >-
            __lazy-wildcards/subject/art-type/sketch-pen-portrait/main__,
            __lazy-wildcards/subject/art-type/sketch-pen-base/prompts__
        main:
          - (Sketch portrait, portrait)
      sketch-pen-base:
        prompts:
          - >-
            __lazy-wildcards/subject/art-type/sketch-pen-base/main__,
            {__lazy-wildcards/subject/art-type/sketch-pen-base/style-color__,|}
            ({3-$$__lazy-wildcards/subject/art-type/sketch-pen-base/style__})
        main:
          - (XCYP) Sketch, (Sketch:1.4), (Pen Drawing:2)
        style-color:
          - >-
            (Black and White Pen Drawing:2)
            {, (Strong Black and White Contrast)|}
        style:
          - High Summary
          - Minimalist Style
          - Thick Lines
          - Smooth Lines
          - Clean
          - Perfect Composition
          - High Contrast
          - Strong Contrast
          - pencil sketch
          - charcoal sketch

```
